version: "3.8"
services:
  frontend:
    image: ecommerce-frontend
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - ecommerce-network
  backend:
    image: ecommerce-backend
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      FLASK_ENV: development
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ecommerce-network
  dns:
    image: ecommerce-dns
    build: ./dns
    ports:
      - "3002:3002"
    networks:
      - ecommerce-network
  db:
    image: ecommerce-db
    build: ./db
    ports:
      - "5432:5432"
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  ecommerce-network:
    driver: bridge
